version: '3.2'

services:
  transmissionapp_web:
    image: kosrabt/transmissionapp_web 
    depends_on:
      - transmissionapp_api
    environment:
      - "ApiUrl=http://transmissionapp_api"
    volumes:
      - type: volume
        source: config
        target: /app/transmissionrss-config
    

  transmissionapp_api:
    image: kosrabt/transmissionapp_api  

  transmissionapp_runner:
    image: kosrabt/transmissionapp_runner   
    depends_on:
      - transmissionapp_api
    environment:
      - "ApiUrl=http://transmissionapp_api"

  
volumes:
  config:
